server:
  port: 8181
  servlet:
    context-path: /movie

movie:
  infoUrl: http://movie-info-service/movie/info/
  ratingUrl : http://movie-rating-service/movie/rating/

spring:
  application:
    name: movie-catalog-service

eureka:
  instance:
    preferIpAddress: true
